module.exports = [
  {
    user_num: 1,
    user_id: "admin",
    user_pw: "admin",
    user_name: "관리자",
    gender: "없음",
    birthday: "230414",
    email: "kosmo",
    domain: "gmail.com",
    phone_num_head: "010",
    phone_num_middle: "1234",
    phone_num_last: "1234",
    user_address: "월드메르디앙 2차",
    isLogin: 1,
  },
  {
    user_num: 22,
    user_id: "cjck12",
    user_pw: "123456",
    user_name: "윤여정",
    gender: "male",
    birthday: "920814",
    email: "cjck12",
    domain: "naver.com",
    phone_num_head: "010",
    phone_num_middle: "3256",
    phone_num_last: "8310",
    user_address: "우리집",
    isLogin: 0,
  },
  {
    user_num: 26,
    user_id: "guswjd",
    user_pw: "123456",
    user_name: "이현정",
    gender: "female",
    birthday: "961001",
    email: "guswjd",
    domain: "gmail.com",
    phone_num_head: "010",
    phone_num_middle: "2629",
    phone_num_last: "5927",
    user_address: "서울역 1번출구",
    isLogin: 0,
  },
  {
    user_num: 27,
    user_id: "codus",
    user_pw: "123456",
    user_name: "김채연",
    gender: "male",
    birthday: "96년언젠가",
    email: "codus",
    domain: "naver.com",
    phone_num_head: "010",
    phone_num_middle: "9163",
    phone_num_last: "9445",
    user_address: "합정역 3번출구",
    isLogin: 0,
  },
  {
    user_num: 28,
    user_id: "asdf",
    user_pw: "asdf",
    user_name: "나제영",
    gender: "male",
    birthday: "19970805",
    email: "",
    domain: "",
    phone_num_head: "",
    phone_num_middle: "",
    phone_num_last: "",
    user_address: "",
    isLogin: 0,
  },
];
