export var seat = {
  seatGrade: [
    { seatGrade: "common", codNm: "일반석" },
    { seatGrade: "unique", codNm: "특화석" },
    { seatGrade: "SKYBOX", codNm: "스카이박스(10인)" },
  ],
  seatName: [
    /* 일반석 */

    { seatGrade: "common", seatName: "2", codNm: "내야지정석(1F)" },
    { seatGrade: "common", seatName: "3", codNm: "내야지정석(2F)" },
    { seatGrade: "common", seatName: "4", codNm: "외야커플석" },
    { seatGrade: "common", seatName: "5", codNm: "외야지정석" },
    /*특화석 */
    { seatGrade: "unique", seatName: "1", codNm: "포수후면석" },
    { seatGrade: "unique", seatName: "2", codNm: "중앙탁자석" },
    { seatGrade: "unique", seatName: "3", codNm: "중앙탁자석A" },
    { seatGrade: "unique", seatName: "4", codNm: "중앙가족석" },
    { seatGrade: "unique", seatName: "5", codNm: "내야응원단석" },
    { seatGrade: "unique", seatName: "6", codNm: "내야탁자석" },
    { seatGrade: "unique", seatName: "7", codNm: "내야하단탁자석" },
    { seatGrade: "unique", seatName: "8", codNm: "중앙메디칼존(내야커플석)" },
    { seatGrade: "unique", seatName: "9", codNm: "VIP커플석" },
    { seatGrade: "unique", seatName: "10", codNm: "덕아웃지정석" },
    { seatGrade: "unique", seatName: "11", codNm: "익사이팅존" },
    { seatGrade: "unique", seatName: "12", codNm: "익사이팅커플석" },
    { seatGrade: "unique", seatName: "13", codNm: "불펜지정석" },
    { seatGrade: "unique", seatName: "14", codNm: "외야라운지석" },
    { seatGrade: "unique", seatName: "15", codNm: "스테이인터뷰존" },
    { seatGrade: "unique", seatName: "16", codNm: "잔디석" },
    { seatGrade: "unique", seatName: "17", codNm: "필드박스(1인)" },
    { seatGrade: "unique", seatName: "18", codNm: "미니박스" },
    /*스카이박스*/
    { seatGrade: "SKYBOX", seatName: "1", codNm: "스카이박스(10인)" },
  ],

  seatNum: [
    /* 내야지정석 (1F) */
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "101",
      codNm: "101",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "102",
      codNm: "102",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "103",
      codNm: "103",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "104",
      codNm: "104",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "105",
      codNm: "105",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "111",
      codNm: "111",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "112",
      codNm: "112",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "301",
      codNm: "301",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "302",
      codNm: "302",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "303",
      codNm: "303",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "304",
      codNm: "304",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "305",
      codNm: "305",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "311",
      codNm: "311",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "312",
      codNm: "312",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "313",
      codNm: "313",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "314",
      codNm: "314",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "315",
      codNm: "315",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "316",
      codNm: "316",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "317",
      codNm: "317",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "318",
      codNm: "318",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "319",
      codNm: "319",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "2",
      seatNum: "320",
      codNm: "320",
      price: 11000,
    },
    /* 내야지정석 (2F) */
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "201",
      codNm: "201",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "202",
      codNm: "202",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "203",
      codNm: "203",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "204",
      codNm: "204",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "205",
      codNm: "205",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "206",
      codNm: "206",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "207",
      codNm: "207",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "208",
      codNm: "208",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "209",
      codNm: "209",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "401",
      codNm: "401",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "402",
      codNm: "402",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "403",
      codNm: "403",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "404",
      codNm: "404",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "405",
      codNm: "405",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "406",
      codNm: "406",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "407",
      codNm: "407",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "408",
      codNm: "408",
      price: 11000,
    },
    {
      seatGrade: "common",
      seatName: "3",
      seatNum: "409",
      codNm: "409",
      price: 11000,
    },
    /*외야 커플석 */
    {
      seatGrade: "common",
      seatName: "4",
      seatNum: "122",
      codNm: "122",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "4",
      seatNum: "123",
      codNm: "123",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "4",
      seatNum: "124",
      codNm: "124",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "4",
      seatNum: "125",
      codNm: "125",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "4",
      seatNum: "126",
      codNm: "126",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "4",
      seatNum: "127",
      codNm: "127",
      price: 9000,
    },
    /*외야 지정석*/
    {
      seatGrade: "common",
      seatName: "5",
      seatNum: "121",
      codNm: "121",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "5",
      seatNum: "122",
      codNm: "122",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "5",
      seatNum: "123",
      codNm: "123",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "5",
      seatNum: "124",
      codNm: "124",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "5",
      seatNum: "125",
      codNm: "125",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "5",
      seatNum: "126",
      codNm: "126",
      price: 9000,
    },
    {
      seatGrade: "common",
      seatName: "5",
      seatNum: "127",
      codNm: "127",
      price: 9000,
    },
    /* 포수후면석 (라이프플러스존) */
    {
      seatGrade: "unique",
      seatName: "1",
      seatNum: "S01",
      codNm: "S01",
      price: 45000,
    },
    {
      seatGrade: "unique",
      seatName: "1",
      seatNum: "S02",
      codNm: "S02",
      price: 45000,
    },
    {
      seatGrade: "unique",
      seatName: "1",
      seatNum: "S03",
      codNm: "S03",
      price: 50000,
    },
    {
      seatGrade: "unique",
      seatName: "1",
      seatNum: "S04",
      codNm: "S04",
      price: 45000,
    },
    {
      seatGrade: "unique",
      seatName: "1",
      seatNum: "S05",
      codNm: "S05",
      price: 45000,
    },
    /* 중앙탁자석 */
    {
      seatGrade: "unique",
      seatName: "2",
      seatNum: "A01",
      codNm: "A01",
      price: 28000,
    },
    {
      seatGrade: "unique",
      seatName: "2",
      seatNum: "A02",
      codNm: "A02",
      price: 28000,
    },
    {
      seatGrade: "unique",
      seatName: "2",
      seatNum: "A03",
      codNm: "A03",
      price: 28000,
    },
    {
      seatGrade: "unique",
      seatName: "2",
      seatNum: "A04",
      codNm: "A04",
      price: 28000,
    },
    {
      seatGrade: "unique",
      seatName: "2",
      seatNum: "A05",
      codNm: "A05",
      price: 28000,
    },
    /* 중앙탁자석 A */
    {
      seatGrade: "unique",
      seatName: "3",
      seatNum: "A01",
      codNm: "A01",
      price: 33000,
    },
    {
      seatGrade: "unique",
      seatName: "3",
      seatNum: "A02",
      codNm: "A02",
      price: 33000,
    },
    {
      seatGrade: "unique",
      seatName: "3",
      seatNum: "A03",
      codNm: "A03",
      price: 33000,
    },
    {
      seatGrade: "unique",
      seatName: "3",
      seatNum: "A04",
      codNm: "A04",
      price: 33000,
    },
    {
      seatGrade: "unique",
      seatName: "3",
      seatNum: "A05",
      codNm: "A05",
      price: 33000,
    },
    /*중앙가족석 */
    {
      seatGrade: "unique",
      seatName: "4",
      seatNum: "A06",
      codNm: "A06",
      price: 25000,
    },
    {
      seatGrade: "unique",
      seatName: "4",
      seatNum: "A07",
      codNm: "A07",
      price: 25000,
    },
    /*내야응원단석*/
    {
      seatGrade: "unique",
      seatName: "5",
      seatNum: "113",
      codNm: "113",
      price: 13000,
    },
    {
      seatGrade: "unique",
      seatName: "5",
      seatNum: "114",
      codNm: "114",
      price: 13000,
    },
    {
      seatGrade: "unique",
      seatName: "5",
      seatNum: "115",
      codNm: "115",
      price: 13000,
    },
    {
      seatGrade: "unique",
      seatName: "5",
      seatNum: "116",
      codNm: "116",
      price: 13000,
    },
    /*내야탁자석 */
    {
      seatGrade: "unique",
      seatName: "6",
      seatNum: "100",
      codNm: "100",
      price: 25000,
    },
    {
      seatGrade: "unique",
      seatName: "6",
      seatNum: "300",
      codNm: "300",
      price: 25000,
    },
    /*내야하단탁자석 */
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "110",
      codNm: "110",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "111",
      codNm: "111",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "112",
      codNm: "112",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "310",
      codNm: "310",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "311",
      codNm: "311",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "312",
      codNm: "312",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "313",
      codNm: "313",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "314",
      codNm: "314",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "315",
      codNm: "315",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "316",
      codNm: "316",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "317",
      codNm: "317",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "318",
      codNm: "318",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "319",
      codNm: "319",
      price: 15000,
    },
    {
      seatGrade: "unique",
      seatName: "7",
      seatNum: "320",
      codNm: "320",
      price: 15000,
    },
    /* 내야커플석 */
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "111",
      codNm: "111",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "112",
      codNm: "112",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "311",
      codNm: "311",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "312",
      codNm: "312",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "313",
      codNm: "313",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "314",
      codNm: "314",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "315",
      codNm: "315",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "316",
      codNm: "316",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "317",
      codNm: "317",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "318",
      codNm: "318",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "319",
      codNm: "319",
      price: 22000,
    },
    {
      seatGrade: "unique",
      seatName: "8",
      seatNum: "320",
      codNm: "320",
      price: 22000,
    },
    /* vip커플석 */
    {
      seatGrade: "unique",
      seatName: "9",
      seatNum: "110",
      codNm: "110",
      price: 50000,
    },
    {
      seatGrade: "unique",
      seatName: "9",
      seatNum: "310",
      codNm: "310",
      price: 50000,
    },
    /* 덕아웃지정석 */
    {
      seatGrade: "unique",
      seatName: "10",
      seatNum: "110",
      codNm: "110",
      price: 12000,
    },
    {
      seatGrade: "unique",
      seatName: "10",
      seatNum: "310",
      codNm: "310",
      price: 12000,
    },
    /* 익사이팅존 */
    {
      seatGrade: "unique",
      seatName: "11",
      seatNum: "106",
      codNm: "106",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "11",
      seatNum: "107",
      codNm: "107",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "11",
      seatNum: "108",
      codNm: "108",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "11",
      seatNum: "109",
      codNm: "109",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "11",
      seatNum: "306",
      codNm: "306",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "11",
      seatNum: "307",
      codNm: "307",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "11",
      seatNum: "308",
      codNm: "308",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "11",
      seatNum: "309",
      codNm: "309",
      price: 20000,
    },
    /* 익사이팅커플석 */
    {
      seatGrade: "unique",
      seatName: "12",
      seatNum: "106",
      codNm: "106",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "12",
      seatNum: "107",
      codNm: "107",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "12",
      seatNum: "108",
      codNm: "108",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "12",
      seatNum: "109",
      codNm: "109",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "12",
      seatNum: "306",
      codNm: "306",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "12",
      seatNum: "307",
      codNm: "307",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "12",
      seatNum: "308",
      codNm: "308",
      price: 20000,
    },
    {
      seatGrade: "unique",
      seatName: "12",
      seatNum: "309",
      codNm: "309",
      price: 20000,
    },
    /* 불펜지정석 */
    {
      seatGrade: "unique",
      seatName: "13",
      seatNum: "323A",
      codNm: "323A",
      price: 12000,
    },
    /* 외야라운지석 */
    {
      seatGrade: "unique",
      seatName: "14",
      seatNum: "327",
      codNm: "327",
      price: 20000,
    },
    /* 스테이인터뷰존 */
    {
      seatGrade: "unique",
      seatName: "15",
      seatNum: "133",
      codNm: "133",
      price: 30000,
    },
    /* 잔디석 */
    {
      seatGrade: "unique",
      seatName: "16",
      seatNum: "128",
      codNm: "128",
      price: 30000,
    },
    {
      seatGrade: "unique",
      seatName: "16",
      seatNum: "326",
      codNm: "326",
      price: 30000,
    },
    /* 필드박스(1인) */
    {
      seatGrade: "unique",
      seatName: "17",
      seatNum: "FIELD1",
      codNm: "FIELD1",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "17",
      seatNum: "FIELD2",
      codNm: "FIELD2",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "17",
      seatNum: "FIELD3",
      codNm: "FIELD3",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "17",
      seatNum: "FIELD4",
      codNm: "FIELD4",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "17",
      seatNum: "FIELD5",
      codNm: "FIELD5",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "17",
      seatNum: "FIELD6",
      codNm: "FIELD6",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "17",
      seatNum: "FIELD7",
      codNm: "FIELD7",
      price: 40000,
    },
    /* 미니박스 */
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M01",
      codNm: "M01",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M02",
      codNm: "M02",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M03",
      codNm: "M03",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M04",
      codNm: "M04",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M05",
      codNm: "M05",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M06",
      codNm: "M06",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M07",
      codNm: "M07",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M08",
      codNm: "M08",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M09",
      codNm: "M09",
      price: 40000,
    },
    {
      seatGrade: "unique",
      seatName: "18",
      seatNum: "M10",
      codNm: "M10",
      price: 40000,
    },
    /* 스카이박스 */
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY01",
      codNm: "SKY01",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY02",
      codNm: "SKY02",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY03",
      codNm: "SKY03",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY04",
      codNm: "SKY04",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY05",
      codNm: "SKY05",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY06",
      codNm: "SKY06",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY07",
      codNm: "SKY07",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY08",
      codNm: "SKY08",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY09",
      codNm: "SKY09",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY10",
      codNm: "SKY10",
      price: 60000,
    },
    {
      seatGrade: "SKYBOX",
      seatName: "1",
      seatNum: "SKY11",
      codNm: "SKY11",
      price: 60000,
    },
  ],
};
